name: CI

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: 'x64'

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Set up poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies
        run: poetry install

      - name: Check safety
        run: poetry run safety check --full-report

      - name: Running tests
        run: poetry run pytest

      - name: Save Coverage
        run: |
          mkdir -p /tmp/coverage-reports
          mv ./coverage.xml /tmp/coverage-reports/${{ matrix.component }}-coverage.xml
          mv ./junit/junit.xml /tmp/coverage-reports/${{ matrix.component }}-junit.xml

      - uses: actions/upload-artifact@v1
        with:
          name: Coverage Reports
          path: /tmp/coverage-reports

  upload-coverage-reports:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1

      - uses: actions/download-artifact@v1
        with:
          name: Coverage Reports
          path: /tmp/coverage-reports

      - name: Copy Coverage Reports
        run: cp /tmp/coverage-reports/*.xml .

      - uses: codecov/codecov-action@v1
        with:
          token: a8ef5bf0-4a4c-47ea-ad45-263fa7495935
          fail_ci_if_error: false
