name: PiPY Publish

on:
  release:
  push:
    tags:
      - "*"
jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name : Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: 'x64'

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Set up poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Set tag version
        run: make version=${GITHUB_REF/refs\/tags\//} version
      
      - name: Build
        run: poetry build

      - name: Pypi Publish
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
