name: PiPY Publish

on:
  push:
    tags:
      - '*'
jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set tag version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:11}

      - name : Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: 'x64'

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Set up poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Set tag version
        run: make version=${{ steps.vars.outputs.tag }} version
      
      - name: Build
        run: poetry build

      - name: Pypi Publish
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
